/**
 * <p>
 * Central provisioning functions used for building adapters that enable human 
 * operators to manage configuration using different protocols.
 * </p>
 * 
 * <p>
 * Such adapters are envisioned to expose configuration management capability using 
 * for example REST, Web Services, SNMP, NETCONF, Command-Line, branded or/and autogenerated 
 * GUI etc.  
 * <p>
 *     
 */
package org.deephacks.confit.admin;

;